
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author israe
 */
public class TelaLuta extends javax.swing.JFrame {

    Lutador l[] = new Lutador[6];
    DefaultListModel lista1 = new DefaultListModel();
    DefaultListModel lista2 = new DefaultListModel();
    String nomeLut1;
    String nomeLut2;
    int numLut1;
    int numLut2;
    

    
    
    
    
    public TelaLuta() {
        initComponents();
        
    l[0] = new Lutador("Pretty Boy", "França", 31, 1.75f, 68.9f, 11, 2, 1);
    l[1] = new Lutador("Putscript", "Brasil", 29, 1.68f, 57.8f, 14, 2, 3);
    l[2] = new Lutador("Snapshadow", "EUA", 35, 1.65f, 80.9f, 12, 2, 1);
    l[3] = new Lutador("Dead Code", "Austrália", 28, 1.93f, 81.6f, 13, 0, 2);
    l[4] = new Lutador("UF0Cobol", "Brasil", 37, 1.70f, 119.3f, 5, 4, 3);
    l[5] = new Lutador("Nerdaart", "EUA", 30, 1.81f, 105.7f, 12, 2, 4); 
        
        
          for (int cont = 0; cont <= 5; cont++){
            String n1 = l[cont].getNome();
            String n2 = l[cont].getNome();
            lista1.addElement(n1);
            lista2.addElement(n2);
             
    
          }
    
          jLista1.setModel(lista1);
          jLista2.setModel(lista2);
    
    }
    

 
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lLutador1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lLutador2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLista1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLista2 = new javax.swing.JList<>();
        lIdade1 = new javax.swing.JLabel();
        lPeso1 = new javax.swing.JLabel();
        lNac1 = new javax.swing.JLabel();
        lAltura1 = new javax.swing.JLabel();
        lCat1 = new javax.swing.JLabel();
        lPeso2 = new javax.swing.JLabel();
        lNac2 = new javax.swing.JLabel();
        lAltura2 = new javax.swing.JLabel();
        lCat2 = new javax.swing.JLabel();
        lIdade2 = new javax.swing.JLabel();
        tIdade1 = new javax.swing.JLabel();
        tNac1 = new javax.swing.JLabel();
        tAltura1 = new javax.swing.JLabel();
        tPeso1 = new javax.swing.JLabel();
        tCat1 = new javax.swing.JLabel();
        tAltura2 = new javax.swing.JLabel();
        tPeso2 = new javax.swing.JLabel();
        tCat2 = new javax.swing.JLabel();
        tIdade2 = new javax.swing.JLabel();
        tNac2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lLutador1.setForeground(new java.awt.Color(0, 0, 0));
        lLutador1.setText("Escolha o lutador 1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bem-vindos ao sistema de luta");

        lLutador2.setForeground(new java.awt.Color(0, 0, 0));
        lLutador2.setText("Escolha o lutador 2");

        jLista1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLista1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLista1);

        jLista2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLista2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jLista2);

        lIdade1.setForeground(new java.awt.Color(102, 0, 0));
        lIdade1.setText("Idade:");

        lPeso1.setForeground(new java.awt.Color(102, 0, 0));
        lPeso1.setText("Peso:");

        lNac1.setForeground(new java.awt.Color(102, 0, 0));
        lNac1.setText("Nac:");

        lAltura1.setForeground(new java.awt.Color(102, 0, 0));
        lAltura1.setText("Altura:");

        lCat1.setForeground(new java.awt.Color(102, 0, 0));
        lCat1.setText("Cat:");

        lPeso2.setForeground(new java.awt.Color(102, 0, 0));
        lPeso2.setText("Peso:");

        lNac2.setForeground(new java.awt.Color(102, 0, 0));
        lNac2.setText("Nac:");

        lAltura2.setForeground(new java.awt.Color(102, 0, 0));
        lAltura2.setText("Altura:");

        lCat2.setForeground(new java.awt.Color(102, 0, 0));
        lCat2.setText("Cat:");

        lIdade2.setForeground(new java.awt.Color(102, 0, 0));
        lIdade2.setText("Idade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lIdade1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tIdade1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lLutador1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCat1)
                                .addGap(18, 18, 18)
                                .addComponent(tCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lAltura1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lNac1)
                                .addGap(18, 18, 18)
                                .addComponent(tNac1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lPeso1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lLutador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lNac2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tNac2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lIdade2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tIdade2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lCat2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tCat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lPeso2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lAltura2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tAltura2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLutador1)
                    .addComponent(lLutador2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNac1)
                            .addComponent(tNac1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lIdade1)
                            .addComponent(tIdade1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lAltura1)
                                    .addComponent(tAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lPeso1))
                            .addComponent(tPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCat1)
                            .addComponent(tCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNac2)
                            .addComponent(tNac2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lIdade2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lAltura2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tIdade2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(tAltura2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPeso2)
                            .addComponent(tPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCat2))
                        .addGap(18, 18, 18)))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLista1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLista1MouseClicked
    //nomeLut1 = jLista1.getSelectionModel();
    numLut1 = jLista1.getSelectedIndex();
    tNac1.setText(l[numLut1].getNacionalidade());
    tIdade1.setText(Integer.toString(l[numLut1].getIdade()));
    tAltura1.setText(Float.toString(l[numLut1].getAltura()));
    tPeso1.setText(Float.toString(l[numLut1].getPeso()));
    tCat1.setText(l[numLut1].getCategoria());

        // TODO add your handling code here:
    }//GEN-LAST:event_jLista1MouseClicked

    private void jLista2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLista2MouseClicked
    numLut2 = jLista2.getSelectedIndex();
    tNac2.setText(l[numLut2].getNacionalidade());
    tIdade2.setText(Integer.toString(l[numLut2].getIdade()));
    tAltura2.setText(Float.toString(l[numLut2].getAltura()));
    tPeso2.setText(Float.toString(l[numLut2].getPeso()));
    tCat2.setText(l[numLut2].getCategoria());
    }//GEN-LAST:event_jLista2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
    
    //jLista1.setModel(lista1); 
    //jLista2.setModel(lista2);
    
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jLista1;
    private javax.swing.JList<String> jLista2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lAltura1;
    private javax.swing.JLabel lAltura2;
    private javax.swing.JLabel lCat1;
    private javax.swing.JLabel lCat2;
    private javax.swing.JLabel lIdade1;
    private javax.swing.JLabel lIdade2;
    private javax.swing.JLabel lLutador1;
    private javax.swing.JLabel lLutador2;
    private javax.swing.JLabel lNac1;
    private javax.swing.JLabel lNac2;
    private javax.swing.JLabel lPeso1;
    private javax.swing.JLabel lPeso2;
    private javax.swing.JLabel tAltura1;
    private javax.swing.JLabel tAltura2;
    private javax.swing.JLabel tCat1;
    private javax.swing.JLabel tCat2;
    private javax.swing.JLabel tIdade1;
    private javax.swing.JLabel tIdade2;
    private javax.swing.JLabel tNac1;
    private javax.swing.JLabel tNac2;
    private javax.swing.JLabel tPeso1;
    private javax.swing.JLabel tPeso2;
    // End of variables declaration//GEN-END:variables
}
