
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author israe
 */
public class ContadorSwing extends javax.swing.JFrame {

    /**
     * Creates new form ContadorSwing
     */
    public ContadorSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinnerInicio = new javax.swing.JSlider();
        spinnerFim = new javax.swing.JSlider();
        spinnerIntervalo = new javax.swing.JSlider();
        lblFim = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblIntervalo = new javax.swing.JLabel();
        btnContar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Início");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 16, -1, -1));

        jLabel2.setText("Fim");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 54, -1, -1));

        jLabel3.setText("Intervalo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, -1, -1));

        spinnerInicio.setMaximum(6);
        spinnerInicio.setValue(0);
        spinnerInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerInicioStateChanged(evt);
            }
        });
        getContentPane().add(spinnerInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 16, -1, -1));

        spinnerFim.setMaximum(20);
        spinnerFim.setMinimum(6);
        spinnerFim.setValue(6);
        spinnerFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerFimStateChanged(evt);
            }
        });
        getContentPane().add(spinnerFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 50, -1, -1));

        spinnerIntervalo.setMaximum(10);
        spinnerIntervalo.setMinimum(1);
        spinnerIntervalo.setValue(1);
        spinnerIntervalo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerIntervaloStateChanged(evt);
            }
        });
        getContentPane().add(spinnerIntervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        lblFim.setText("6");
        getContentPane().add(lblFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 54, 38, -1));

        lblInicio.setText("0");
        getContentPane().add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 20, 30, -1));

        lblIntervalo.setText("1");
        getContentPane().add(lblIntervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 40, -1));

        btnContar.setText("Contar");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jScrollPane2.setViewportView(txtArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 90, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        // TODO add your handling code here:
        int inicio = spinnerInicio.getValue();
        int fim = spinnerFim.getValue();
        int intervalo = spinnerIntervalo.getValue();
        
        DefaultListModel lista = new DefaultListModel();
        
        for (int inicio2 = inicio; inicio2 <= fim; inicio2 += intervalo){
            lista.addElement(inicio2);
        }
        
        txtArea.setModel(lista);
        
    }//GEN-LAST:event_btnContarActionPerformed

    private void spinnerInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerInicioStateChanged
        // TODO add your handling code here:
        String nInicio = new String();
        nInicio = Integer.toString(spinnerInicio.getValue());
        lblInicio.setText(nInicio);
    }//GEN-LAST:event_spinnerInicioStateChanged

    private void spinnerFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerFimStateChanged
        // TODO add your handling code here:
        lblFim.setText(Integer.toString(spinnerFim.getValue()));
    }//GEN-LAST:event_spinnerFimStateChanged

    private void spinnerIntervaloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerIntervaloStateChanged
        // TODO add your handling code here:
        lblIntervalo.setText(Integer.toString(spinnerIntervalo.getValue()));
    }//GEN-LAST:event_spinnerIntervaloStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContadorSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblIntervalo;
    private javax.swing.JSlider spinnerFim;
    private javax.swing.JSlider spinnerInicio;
    private javax.swing.JSlider spinnerIntervalo;
    private javax.swing.JList<String> txtArea;
    // End of variables declaration//GEN-END:variables
}
